stages:
    - build
    - deploy

build:
    image: gradle:jdk17
    stage: build
    only:
        - main
    artifacts:
        paths:
            - ./build/libs
    variables:
        USERNAME: $NEXUS_USER
        PASSWORD: $NEXUS_PWD
        VERSION: $CI_COMMIT_SHORT_SHA
    script:
        - ./gradlew publish

deploy:
    image: justtreme/lftp:4.8.1
    stage: deploy
    only:
        - main
    dependencies:
        - build
    script:
        - lftp -e "set sftp:auto-confirm yes; mirror -X .* -X .*/ --reverse --verbose ./build/libs /home; bye" -u $SFTP_USER,$SFTP_PWD sftp://89.163.129.221
