language:
  jdbc: 'jdbc:mysql//localhost:3306/laudynetwork'
  user: 'language'
  pwd: 'test123'
playerLanguageData:
  jdbc: 'jdbc:mysql//localhost:3306/laudynetwork'
  user: 'playerLanguage'
  pwd: 'test123'