name: Build and Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Build with Gradle
        run: |
          chmod 777 gradlew
          ./gradlew build
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PWD: ${{ secrets.NEXUS_PWD }}
      - name: Publish to Nexus
        if: github.ref == 'refs/heads/main'
        run: ./gradlew publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PWD: ${{ secrets.NEXUS_PWD }}
      - name: Upload File to Server
        uses: sebastianpopp/ftp-action@v2.0.0
        if: github.ref == 'refs/heads/main'
        with:
          host: 89.163.129.221
          user: root
          password: ${{ secrets.SFTP_PWD }}
          localDir: ./build/dist
          remoteDir: /home/simplecloud/templates/EVERY_SERVER/plugins
