name: Build and Deploy

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Build with Gradle
        run: |
          chmod 777 gradlew
          ./gradlew build
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PWD: ${{ secrets.NEXUS_PWD }}
      - name: Publish to Nexus
        if: github.ref == 'refs/heads/main'
        run: ./gradlew publish
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PWD: ${{ secrets.NEXUS_PWD }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NetworkUtils.jar
          path: ./build/dist/NetworkUtils.jar
      - name: Upload to Server
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PWD }}
          port: 22
          uploads: |
            ./home/runner/_work/NetworkUtils/NetworkUtils/build/dist => /home/simplecloud/templates/EVERY_SERVER/plugins
          ignore: |
            *.git
            */**/*git*
